Frontend/src/pages/BulkPreview/bulk.style.scss
Frontend/src/pages/EditBulk/edit.style.scss
Frontend/src/pages/SinglePreview/singlepreview.style.scss

For my images to be centered, it won't affect any other styling

Updated style.bulk.scss

---

Frontend/src/pages/FAQ/faq.module.scss

Please help me to merge before they start grading us. Abeg

Realigned the faq text to the left

---

Frontend/src/pages/Templates/index.jsx
Frontend/src/pages/Templates/template.style.scss

Fix the button style to address conflicts

style: fix button styling

---

Frontend/src/pages/Templates/template.style.scss

stylefix: update btn styling

---

Frontend/src/pages/Pricing/data.jsx
Frontend/src/pages/Pricing/feature.jsx
Frontend/src/pages/Pricing/index.jsx
Frontend/src/pages/Pricing/pricing.style.scss

I fixed the minor issues highlighted in today’s meeting. As for the slider, I would need to install a package (swiper.js) that is altering the package.json but I was able to make it clear that it was a slider

Minor adjustments to pricing page

---

Frontend/src/App.js
Frontend/src/Component/Footer/footer.style.scss
Frontend/src/Component/Footer/index.jsx
Frontend/src/Component/Navbar/index.jsx
Frontend/src/Component/Navbar/navbar.style.scss
Frontend/src/Style/App.scss
Frontend/src/index.css

proper linking of all pages on the navbar and footer as well as cleanup styling on both component

Navbar and Footer linking

---

Frontend/src/pages/BulkPreview/bulk.style.scss
Frontend/src/pages/BulkPreview/index.jsx
Frontend/src/pages/EditBulk/edit.style.scss
Frontend/src/pages/EditBulk/index.jsx

Aligned the buttons and centered the heading, added slider to the mobile view of bulk preview page

Feat(FRO-25): Modify certificate preview page 

---

Backend/controllers/authController.js
Backend/controllers/userCertificateController.js
Backend/package-lock.json
Backend/routes/certificateRouter.js
package-lock.json
package.json

Req Method: POST
route: addCertificate
endpoint: 'api/certificates'
400 res if no req.body and req.files
400 res if csv file comes with wrong format
200 and json certificate response to client when all conditions are met

FEAT(BE-7): I added form input upload for single certificate for the user

---

Frontend/src/Component/Footer/index.jsx
Frontend/src/Component/Navbar/index.jsx
Frontend/src/Component/Signup-Login/assets/Login.jsx
Frontend/src/Component/Signup-Login/assets/Sginup.jsx
Frontend/src/Data/TermsOfService.js
Frontend/src/pages/AboutUs/index.jsx

Changed name from certawi to certify

fix: Fix some pages name

---

Backend/controllers/pricingController.js
Backend/index.js
Backend/models/pricingModel.js
Backend/package-lock.json
Backend/package.json
Backend/routes/pricingRouter.js

Created four endpoints "/api/pricing". (POST, GET, PUT, DELETE). The post route is for creating the user's pricing plan, which is sent to the frontend with a status code of 201, The GET route is used to get all users and specific user's plan, the update is for updating the user's pricing plan while delete route is for deleting the user's plan
Linear link: https://linear.app/team-headlight/issue/BE-14/endpoints-for-pricing-page

feat(BE-14): added endpoints to pricing page

---

Backend/controllers/userCertificateController.js

I corrected my If/else statement for user's existence

FIX(BE-7): Fix to issue #167

---

Backend/controllers/contactController.js
Backend/index.js
Backend/models/contactModel.js
Backend/routes/contactRouter.js

feat/BE-18-contactus.
This is the contact us endpoint for mailing.
It gets the contact us form details. An email is sent to the client to acknowledge that their message has been received.

feat(BE-18)

---

Backend/models/pricingModel.js
Backend/package-lock.json

Created four endpoints "/api/pricing". (POST, GET, PUT, DELETE). The post route is for creating the user's pricing plan, which is sent to the frontend with a status code of 201, The GET route is used to get all users and specific user's plan, the update is for updating the user's pricing plan while delete route is for deleting the user's plan
Linear link: https://linear.app/team-headlight/issue/BE-14/endpoints-for-pricing-page

fix(BE-14): added endpoints to pricing page

---

Backend/swagger_output.json

Reverts workshopapps/certificategenerator.web#180

Revert "Swagger"

---

Backend/app.js
Backend/package-lock.json
Backend/package.json
Backend/tests/auth.test.js
Backend/tests/careers.test.js
Backend/tests/contactus.test.js
Backend/tests/mailinglist.test.js
Backend/tests/pricing.test.js
Backend/tests/profile.test.js
Backend/tests/testDBConfig.js
Backend/tests/testFiles/bad.csv
Backend/tests/testFiles/bad.pdf
Backend/tests/testFiles/good.csv
Backend/tests/upload.test.js

I wrote unit tests to test the following endpoints
* /api/upload
* /api/contactus
* /api/profile
* /api/malinglists
* /api/careers
* /api/auth
* /api/pricing

test(BE): Setup unittests for backend api endpoints

---

Backend/README.md
Backend/middleware/fileExtLimiter.js

The issue was generated from the fileExtLimiter middleware. The middleware is always expecting a file in the req to the endpoint which was not taken into consideration when the endpoint was upgraded to accept form data

FIX(BE-7): fix to issue #190

---

frontend/src/App.js
frontend/src/pages/UploadCSV/index.jsx

I made a POST request to the "https://certify-api.onrender.com/api/certificates" api endpoint and then passed the response as a prop to the bulk review page.

Integrated the upload csv api with the website

---

frontend/public/index.html
frontend/src/Data/TermsOfService.js
frontend/src/pages/FAQ/FAQcomp/FaqModule.jsx

This commit will update the name of the product from certify to certonic in the pages where it hasn't been changed.

fix: Update product name

---

frontend/src/pages/SinglePreview/index.jsx
frontend/src/pages/SinglePreview/singlepreview.style.scss

got the form-data from the home page into the single certificate preview page and built the certificate

Formdata from homepage to certificate preview page

---

frontend/src/Data/TermsOfService.js
frontend/src/pages/Terms/index.jsx
frontend/yarn.lock

This PR updates the terms of service with the latest updates from the marketing team. 
[Linear link](https://linear.app/team-headlight/issue/FRO-43/create-a-terms-of-service-page)

feat(FRO-43) chore: update terms of service with latest copy

---

Backend/controllers/profileController.js
Backend/models/profileModel.js
Backend/routes/profileRouters.js

https://linear.app/team-headlight/issue/BE-5/user-profile-info-update

Be 5 profile page

---

frontend/cypress/e2e/1-getting-started/todo.cy.js
frontend/cypress/e2e/2-advanced-examples/actions.cy.js
frontend/cypress/e2e/2-advanced-examples/aliasing.cy.js
frontend/cypress/e2e/2-advanced-examples/assertions.cy.js
frontend/cypress/e2e/2-advanced-examples/connectors.cy.js
frontend/cypress/e2e/2-advanced-examples/cookies.cy.js
frontend/cypress/e2e/2-advanced-examples/cypress_api.cy.js
frontend/cypress/e2e/2-advanced-examples/files.cy.js
frontend/cypress/e2e/2-advanced-examples/local_storage.cy.js
frontend/cypress/e2e/2-advanced-examples/location.cy.js
frontend/cypress/e2e/2-advanced-examples/misc.cy.js
frontend/cypress/e2e/2-advanced-examples/navigation.cy.js
frontend/cypress/e2e/2-advanced-examples/network_requests.cy.js
frontend/cypress/e2e/2-advanced-examples/querying.cy.js
frontend/cypress/e2e/2-advanced-examples/spies_stubs_clocks.cy.js
frontend/cypress/e2e/2-advanced-examples/traversal.cy.js
frontend/cypress/e2e/2-advanced-examples/utilities.cy.js
frontend/cypress/e2e/2-advanced-examples/viewport.cy.js
frontend/cypress/e2e/2-advanced-examples/waiting.cy.js
frontend/cypress/e2e/2-advanced-examples/window.cy.js
frontend/cypress/e2e/spec.cy.js
frontend/cypress/fixtures/example.json
frontend/cypress/support/commands.js
frontend/cypress/support/e2e.js

I have written a unit test for the home component by: 
- Using cypress to ensure end to end testing 
- Testing all major components
- Ensuring the end user is able to fully utilize the product

feat(FRO-1): Implemented unit testing

---

frontend/package-lock.json
frontend/package.json
frontend/src/pages/Home/Certificate/index.jsx
frontend/src/pages/SinglePreview/index.jsx
frontend/yarn.lock

Worked on downloading the certificate

feat(FRO-30): Download Single Certificate 

---

frontend/src/Component/inputField/index.jsx
frontend/src/Component/textarea/index.jsx
frontend/src/pages/contactUs/contact.scss
frontend/src/pages/contactUs/index.jsx

Enabled visitors to send messages to the backend

Fro 28 api: Connect Contact-us page to the backend

---

frontend/src/Component/button/button.scss
frontend/src/Component/button/index.jsx
frontend/src/pages/contactUs/index.jsx

replace api address from IP to live link

Feat:Fro 28 api

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.js
frontend/src/Component/index.js
frontend/src/Component/loader/index.jsx
frontend/yarn.lock

This commit will create a general loader component that can be imported whenever it is needed in any part of the application.
https://user-images.githubusercontent.com/50625848/204833971-8bffad04-7c56-4097-ab64-c6b7a4aecb61.mp4
https://user-images.githubusercontent.com/50625848/204834620-62fedc6e-9871-4dc6-a5c7-c1636cb044bd.mp4

feat(FRO-52): Create general loader for the entire website

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.js
frontend/src/Component/index.js
frontend/src/Component/loader/index.jsx
frontend/src/pages/FAQ/faq.module.scss
frontend/src/pages/Home/Testimonials/index.jsx
frontend/src/pages/Home/Testimonials/testimonials.style.scss
frontend/src/pages/Pricing/data.jsx
frontend/src/pages/Pricing/feature.jsx
frontend/src/pages/Pricing/pricing.style.scss
frontend/yarn.lock

-I implemented the marketer's adjustment on the home and pricing page
-Removed the "500+ high performing business partners" on the pricing page
-Changed the plan on the pricing page
-Finally, I added margins between each accordion and also reduced the font-size

FRO-63: Implementation of adjustments on the website

---

frontend/src/pages/SinglePreview/index.jsx
frontend/src/pages/SinglePreview/singlepreview.style.scss

Added modal popup to download option, modal popup to download as PDF or PNG

FRO-70: Create a modal for PDF or PNG format for certificate download

---

frontend/src/pages/Home/Certificate/index.jsx
frontend/src/pages/SinglePreview/index.jsx
frontend/src/pages/SinglePreview/singlepreview.style.scss

Made corrections
Changed Modal to drop down

Modal download for png and pdf

---

Backend/controllers/userCertificateController.js
Backend/models/certificateModel.js
Backend/routes/certificateRouter.js

I worked on a new endpoint to update the status a specific certificate of a user
HTTP request = PATCH
user certificate status default = "pending"
user certificate acceptable status = "pending", "issued", "canceled"
Request body key = status
Request body example = { status: "pending" }
response status on success = 200
response if request body is rejected = 400

FEAT(BE-39): I added an endpoint to update certificate status

---

Backend/controllers/userCertificateController.js
Backend/routes/certificateRouter.js

FIX(BE-39): fixed ID  bug in my #237 pull request

---

frontend/src/Component/Input/index.jsx
frontend/src/Component/Input/input.style.scss

This commit  will add the form input component and also fix override issues.

feat: Add form input component

---

frontend/src/App.js

This commit will change the set timeout from 5000 to 1000

fix(FRO-52): Reduce the loader timeout

---

Backend/controllers/userCertificateController.js

BE-10 https://linear.app/team-headlight/issue/BE-10/to-work-on-the-dashboard-page-3
Deleting of single certificate:
After review from mentors and a colleague, I was told it contain a bug so I had to quickly fix it before moving forward

fix: Certificate delete endpoint issue fixed

---

Backend/controllers/eventController.js
Backend/controllers/userCertificateController.js
Backend/index.js
Backend/middleware/authentication.js
Backend/middleware/fileExtLimiter.js
Backend/models/certificateModel.js
Backend/models/eventModel.js
Backend/routes/eventRouter.js
Backend/tests/testFiles/good.csv
Backend/utils/validation.js

* Setup database model for events
* An event connects a certification collection with a customURI
* The custom URI is a string that uniquely identifies this event, it doesn't represent a full url e.g "hackFest" would pass as a customURI. More on this later...
* The customURI is optional, when it's not provided, the event can be access via the event _id
* Setup CRUD endpoints for events
* User must be signed in to access the following endpoints
* GET /api/events - get all events created by this user
* POST /api/events - create a new event for an existing certificate collection
* DELETE /api/events/:id - delete an event by id
* PATCH  /api/events - edit an event (only the title and customURI can be changed)
* The following endpoints can be accessed without the user being logged in
* GET …

Be 66 generate link for each certificate in user dashboard

---

Backend/controllers/applyCareerController.js
Backend/index.js
Backend/models/ApplycareerModel.js
Backend/routes/applyCareerRouter.js
Backend/utils/email.js

The endpoints i provided will enable the Users to be able to apply through pop-up form and fill a form to apply and they will be sent  mail after applying to any provided careers on the website

feat(BE-65): added endpoints for enable user apply to careers

---

frontend/src/pages/Home/Certificate/certificate.style.scss
frontend/src/pages/Home/Certificate/index.jsx

I added a disabled state to the button when it is disabled

create certificate button disabled without required input

---

frontend/src/pages/Home/Testimonials/index.jsx
frontend/src/pages/Home/Testimonials/testimonials.style.scss
frontend/src/pages/SinglePreview/index.jsx
frontend/src/pages/SinglePreview/singlepreview.style.scss

Explore template button on single preview page is now visible and centred
Testimonial carousel is responsive

Adjusted explore template button and testimonial

---

frontend/src/Component/inputField/input.scss
frontend/src/pages/contactUs/contact.scss

add appearance none to input number type and ensure it works across browsers

Fro 55: fix phone text field on contact page

---

Backend/controllers/emailNotificationController.js
Backend/index.js
Backend/routes/emailNotificationRouter.js

Users should be able to send certificates pdf to their email after creating and receive email notification immediately.
Linear Link : https://linear.app/team-headlight/issue/BE-43/create-endpoint-for-e-mail-notification

feat(BE-43): added endpoint for email notification

---

Backend/controllers/pricingPlanController.js
Backend/index.js
Backend/models/pricingPlanModel.js
Backend/routes/pricingPlanRouter.js

Endpoint to get, post and Update user pricing plan.
linear link: https://linear.app/team-headlight/issue/BE-71/endpoint-to-get-post-and-update-user-pricing-plan

feat(BE-71): added endpoints to pricing-page

---

frontend/src/App.js
frontend/src/Component/Signup-Login/assets/Login.jsx
frontend/src/Component/Signup-Login/assets/Style.css
frontend/src/Component/Signup-Login/assets/Style.scss
frontend/src/pages/Home/Certificate/index.jsx

Registered users can log in
It displays an error if the user is not registered

FRO-89: Integrate endpoint to login with email and password

---

frontend/src/pages/BulkPreview/bulk.style.scss
frontend/src/pages/BulkPreview/index.jsx

I deleted the '120 recipients texts' on the page

edited the text in the h2 tag on the bulk preview page

---

frontend/src/pages/Home/Certificate/index.jsx
frontend/src/pages/SinglePreview/index.jsx
frontend/src/pages/SinglePreview/singlepreview.style.scss

Centered the dropdown buttons that appear when you hover on the download button on the preview page

Centered the dropdown buttons

---

frontend/src/App.js
frontend/src/Component/Signup-Login/assets/Login.jsx
frontend/src/pages/Pricing/data.jsx
frontend/src/pages/Pricing/index.jsx

1. The user clicks on login, 
2. If the email and password are valid, the user is redirected to the pricing page
3. If the user clicks on the Basic plan, the user is redirected to the homepage to get started
4. If the user clicks on the standard or premium plan, the user is redirected to the payment page

Re-routed login page to pricing page

---

Backend/controllers/emailNotificationController.js
Backend/index.js
Backend/routes/emailNotificationRouter.js

Fixed the error on the email Notification Controller
All working Fine

feat(BE-43): fixed added endpoint for email notification

---

frontend/src/pages/BulkPreview/BulkCertDesign/bulkcertdesign.style.scss
frontend/src/pages/BulkPreview/BulkCertDesign/index.jsx
frontend/src/pages/BulkPreview/bulk.style.scss
frontend/src/pages/BulkPreview/index.jsx
frontend/src/pages/Dashboard/index.jsx
frontend/src/pages/SinglePreview/singlepreview.style.scss

I have not used a dummy data to populate yet because I have to go to the mosque... I'll do that as soon as I am back

added the certificate markup design

---

Backend/controllers/authController.js
Backend/controllers/pricingPlanController.js
Backend/routes/pricingPlanRouter.js

Endpoints to update user's subscription plan
linear link: https://linear.app/team-headlight/issue/BE-71/endpoint-to-get-post-and-update-user-pricing-plan

feat(BE-71): added pricing endpoint

---

Backend/controllers/verifyEmailController.js
Backend/index.js
Backend/routes/verifyEmailRouter.js

Feat/BE-60 - Email Verification Via Code
The endpoint sends a link to the email after signing up.
The link in the email verifies the email of the user

Feat/BE-60 - Email Verification Via Code

---

Backend/controllers/profileController.js
Backend/routes/profileRouters.js

**Task completed in this PR**
- Added authentication middleware so that only user that is already logged in can 
1.  create profile
2. view profile
3. update profile
4. Delete profile

feat(BE-58): user profile update and delete

---

Backend/controllers/paymentController.js
Backend/index.js
Backend/package.json
Backend/routes/paymentRouter.js

Feat/BE-55 - Payment Implementation 
Paystack Integration for subscription

Feat/BE-55 - Payment Implementation 

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.js
frontend/src/pages/Home/Certificate/certificate.style.scss
frontend/src/pages/Home/Certificate/index.jsx
frontend/src/pages/Home/Hero/index.jsx
frontend/src/pages/Preview/index.jsx
frontend/src/pages/SinglePreview/index.jsx
frontend/src/pages/SinglePreview/singlepreview.style.scss
frontend/src/pages/Templates/index.jsx
frontend/src/pages/Templates/modal.jsx
frontend/yarn.lock

Hello team Kindly merge for the certificate type/color picker simultaneous picking task

feat:implementing simultaneous color/certificate type picker

---

Backend/controllers/authController.js
Backend/controllers/templateController.js
Backend/routes/templateRouter.js
Backend/utils/generateToken.js

The endpoint gets one template for a premium user
https://linear.app/team-headlight/issue/BE-68/create-endpoint-for-custom-template-premium-users#comment-0cde5b7a

feat(BE-68): add endpoint to get one template for premium user

---

frontend/package-lock.json
frontend/package.json
frontend/src/pages/Home/BulkStep/BulkStep.style.scss
frontend/src/pages/Home/Certificate/certificate.style.scss
frontend/src/pages/Home/Certificate/index.jsx
frontend/src/pages/Home/Hero/hero.style.scss
frontend/src/pages/Home/Hero/index.jsx
frontend/src/pages/Home/Partners/partners.style.scss
frontend/src/pages/Home/Testimonials/testimonials.style.scss
frontend/yarn.lock

I installed a package for picking date to fix the date picking issue

fixed the date input

---

frontend/src/Component/Footer/index.jsx
frontend/src/pages/UploadCSV/index.jsx
frontend/src/pages/UploadCSV/uploadCSV.style.scss

Hello team kindly merge for error message when invalid file is uploaded in csv upload

feat:error message added in csv

---

frontend/src/Component/Footer/footer.style.scss
frontend/src/Component/Footer/index.jsx

Added a success message to the newsletter subscription
message - You have successfully subscribed for our newsletter🎉

added a response message to the newsletter subscription

---

frontend/src/Component/Navbar/index.jsx

Routed Get started button in the Navbar to the Sign Up page

Routed Get started button 

---

frontend/package-lock.json
frontend/package.json
frontend/src/Component/Signup-Login/assets/Login.jsx
frontend/src/Component/Signup-Login/assets/login.scss
frontend/yarn.lock

Worked on error handling, and adding success message if user data is valid

FRO-89: Worked on error handling on the Login page

---

Backend/controllers/authController.js

<h2>added enpoint that allows users signin with google auth </h2>
- Request type: POST
- Request body parameter: "accessToken"
`{"accessToken":"<access token>"} //google sign up`
- Response: 
- statusCode: 201 (success)
`{message: "user logged in successfully", token: <string>, userId: <string>}`

feat(BE-73): added endpoint for google login

---

Backend/controllers/userCertificateController.js

Endpoint now shows data when certificates are being created

Fix(BE-54): Added certificate lists to endpoint

---

frontend/src/pages/UploadCSV/index.jsx

This pull request will enable the user to send the uploaded file to the backend.
[Screencast from 03-12-2022 15:08:43.webm](https://user-images.githubusercontent.com/50625848/205445648-78d31130-f2dd-47f3-838f-f33687ceeea4.webm)

feat(FRO-94): API implementation for CSV upload

---

frontend/src/pages/Dashboard/CreateCertificateModal/createmodal.style.scss
frontend/src/pages/Dashboard/CreateCertificateModal/index.jsx
frontend/src/pages/Dashboard/Loader/index.jsx

I added a load state in the create certificate button on the modal in the dashboard page

added a load state to the create cert button 

---

frontend/src/pages/BulkPreview/bulk.style.scss

I removed a 1px black border surrounding the slider

removed the border in the bulk preview page

---

Backend/controllers/authController.js

**Tasks completed in this PR**
- Hash password after user reset password to enable login with the new password

fix(BE-69): hash password after user changed password

---

Backend/routes/certificateRouter.js

User be able to delete all certificates on their dashboard

feat(BE-61): delete all user certificates

---

Backend/controllers/userCertificateController.js
Backend/routes/certificateRouter.js

Endpoint to delete all user's certificate on dashboard

fix(BE-61): fixed the delete all user route

---

backend/controllers/userCertificateController.js
backend/routes/certificateRouter.js

Endpoint to delete all user's certificates on their dashboard

fix(BE-61): fixed-delete-user-certificates

---

backend/controllers/userCertificateController.js

fixed delete user certificate controller

fix(BE-61): delete all controller

---

frontend/src/Component/Signup-Login/assets/Login.jsx

changed the loginUser (Google) to loginUserGoogle

Hotfix login

---

backend/controllers/userCertificateController.js

Fixed endpoint that delete all user's certificates

fix(BE-61): fixed delete all user certificates

---

backend/controllers/userCertificateController.js

Fixed endpoint to delete users certificates

fix(BE-61): delete users certificates

---

frontend/src/Component/Signup-Login/assets/Login.jsx
frontend/src/Component/Signup-Login/assets/Sginup.jsx

Adds feedback when user logins in or signs up with Google using Toast

feat (FRO-71): add toast notifications for feedback

---

frontend/src/App.js
frontend/src/pages/Preview/index.jsx
frontend/src/pages/UploadCSV/index.jsx

Upload csv api

---

frontend/src/Component/Signup-Login/assets/Sginup.jsx
frontend/src/Component/Signup-Login/assets/signup.scss

Reverts workshopapps/certificategenerator.web#388

Revert "Revert "Amina/fro 88""

---

frontend/package-lock.json
frontend/src/api/axios.js
frontend/src/pages/Dashboard/CreateCertificateModal/index.jsx
frontend/src/pages/Dashboard/TableRow.jsx
frontend/src/pages/Dashboard/UploadCsv/index.jsx
frontend/src/pages/Dashboard/UploadCsv/uploadcsv.style.scss
frontend/src/pages/Dashboard/dashboard.style.scss
frontend/src/pages/Dashboard/index.jsx
frontend/src/pages/Dashboard/utils/index.js
frontend/yarn.lock

I am getting all user certificates if it is available

Getting all user certificates

---

frontend/package-lock.json
frontend/src/api/axios.js
frontend/src/pages/Dashboard/CreateCertificateModal/index.jsx
frontend/src/pages/Dashboard/TableRow.jsx
frontend/src/pages/Dashboard/UploadCsv/index.jsx
frontend/src/pages/Dashboard/UploadCsv/uploadcsv.style.scss
frontend/src/pages/Dashboard/dashboard.style.scss
frontend/src/pages/Dashboard/index.jsx
frontend/src/pages/Dashboard/utils/index.js
frontend/yarn.lock

I am updating the status from pending to issued

Updating status 

---

backend/controllers/emailNotificationController.js
backend/index.js
backend/package-lock.json
backend/routes/emailNotificationRouter.js

Have fixed the send to the email  and receive notifications part , kindly confirm

feat(BE-43): Fixed the send to email and notification part

---

backend/controllers/emailNotificationController.js

fixed the notification controller

fixed the notification controller

---

frontend/src/pages/Home/Hero/index.jsx
frontend/src/pages/UploadCSV/index.jsx
frontend/src/pages/UploadCSV/sample.csv

This commit will
- Edit the hero text on the landing page
- Add a button for users to download a sample csv to create bulk certificates
https://user-images.githubusercontent.com/50625848/206082739-c6244542-bfa2-46af-9a37-7df8d9943703.mp4

feat: Update landing page

---

frontend/package-lock.json
frontend/src/pages/BulkPreview/BulkCertDesign/index.jsx
frontend/yarn.lock

This commit will remove the logo on the bulk preview page for unauthenticated users

chore: Remove logo

---

frontend/src/App.js
frontend/src/index.js

Change from HashRouter to BrowserRouter

chore: Change router package

---

backend/utils/helpers.js

chore: setup helpers for api controllers

---

backend/models/careerModel.js

added the category to the careers

fixed the career controller

---

backend/controllers/csvController.js
backend/package-lock.json

Made a code cleanup to csvController file

cleanup csvController

---

backend/controllers/profileController.js
backend/routes/profileRouters.js

Refactored and fixed profiles endpoints
* Refactored the endpoints to conform to certgo API standard repsonse format
* Fixed bugs in :
* POST /api/profile
* DELETE /api/profile
* PATCH /api/profile
* Change deleted endpoint from /api/profile/:id to /api/profile removing the need for profile id

fix(BE): refactor and fix profile endpoints

---

backend/controllers/applyCareerController.js
backend/controllers/careerController.js
backend/controllers/emailNotificationController.js
backend/controllers/mailingListController.js
backend/utils/email.js

Refactored    controllers/applyCareerController.js
controllers/careerController.js
controllers/mailingListController.js
utils/email.js

refactor some  controllers

---

backend/controllers/userCertificateController.js

FIX: Removed all .end() functions

removed .end()

---

backend/models/profileModel.js
backend/models/userModel.js

Automatically create a user profile when a new user signs up

feat(BE): create profile for new user on signup

---

backend/controllers/authController.js
backend/controllers/userCertificateController.js
backend/models/userModel.js
backend/routes/certificateRouter.js
frontend/src/Component/Signup-Login/assets/Login.jsx

- Fixed wrong error code and message on user Login
- updated user controller and model to save name
- added endpoint to verify certificate

Auth fix/verify certificate

---

frontend/src/pages/Dashboard/index.jsx

This PR will address the ability for the user to see his/her brandkit on the dashboard page

feat: Add get request to display a user's brandkit

---

frontend/src/pages/Dashboard/index.jsx

[Screencast from 09-12-2022 17:03:35.webm](https://user-images.githubusercontent.com/50625848/206743584-f3c0f603-2100-4194-be13-97eb601330a3.webm)

Add feature for premium users to update brand kit

---

frontend/src/Component/Signup-Login/assets/Signup.jsx
frontend/src/contexts/AppProvider.js
frontend/src/pages/BulkPreview/bulk.style.scss
frontend/src/pages/Dashboard/index.jsx

fixed the bulk preview drop down buttons and fixed profile name

Bulk drop down button

---

backend/controllers/profileController.js
backend/index.js
backend/models/userModel.js
backend/models/userProfileModel.js

**Tasks completed in this PR**
-User  profile update
- User profile delete

fix(BE-58): User profile info update and delete

---

backend/controllers/contactController.js

fixed wrong info on contact controller

---

frontend/src/Component/Signup-Login/assets/Login.jsx
frontend/src/Component/Signup-Login/assets/Signup.jsx

signup with apple

---

frontend/src/Component/Signup-Login/assets/Signup.jsx
frontend/src/contexts/AppProvider.js
frontend/src/pages/Dashboard/Modal/ViewModal/view.style.scss
frontend/src/pages/Dashboard/TableRow.jsx
frontend/src/pages/Dashboard/UploadCsv/index.jsx
frontend/src/pages/Dashboard/UploadCsv/uploadcsv.style.scss
frontend/src/pages/Dashboard/dashboard.style.scss
frontend/src/pages/Dashboard/index.jsx

I removed bugs and some unused codes
The View and Status Change is functional

Refactoring Dashboard 

---

frontend/package-lock.json
frontend/package.json
frontend/src/pages/BulkPreview/BulkCertDesign/BulkCertDesign1.jsx
frontend/src/pages/BulkPreview/BulkCertDesign/BulkCertDesign2.jsx
frontend/src/pages/BulkPreview/BulkCertDesign/BulkCertDesign3.jsx
frontend/src/pages/BulkPreview/index.jsx
frontend/yarn.lock

https://user-images.githubusercontent.com/50625848/206862226-31cb636e-3805-46fe-b8ff-90f96df959c1.mp4

feat: Add feature to enable users download pdf certificates in bulk

---

frontend/src/pages/ProfilePage/index.jsx
frontend/src/pages/ProfilePage/profile.style.scss

Some details on the profile page are agreed to be scrapped

fix: removed unimportant details in the profile page

---

backend/controllers/profileController.js
backend/routes/profileRouters.js

I setup and endpoint to get a user's avatar

feat: setup endpoint to get user avatar

---

frontend/src/pages/BulkPreview/index.jsx

fix: Fix modal text on bulk preview page

---

frontend/src/pages/Dashboard/index.jsx

The user's plan can now be viewed on the dashboard.

fix: rendered user's plan on the dashboard

---

frontend/src/pages/BulkPreview/index.jsx
frontend/src/pages/Dashboard/index.jsx
frontend/src/pages/UploadCSV/index.jsx

I am getting the unauthorized users bulk certificates generated after the user logs in

Getting the bulk certificates on the dashboard

---

backend/controllers/authController.js

Set status code for no name to 400

fix: correct status code for name is required

---

frontend/src/pages/Checkout/components/CheckoutMain.jsx
frontend/src/pages/Checkout/components/CheckoutMainLeft.jsx

The user's plan rendered is now based on the pricing selected.

feat: updated rendering user's plan to be dynamic

---

frontend/package-lock.json
frontend/src/pages/ProfilePage/modalpage.jsx
frontend/src/pages/ProfilePage/profile.style.scss
frontend/yarn.lock

Kindly merge the Modified profile page

feat:profile modification

---

frontend/src/pages/ProfilePage/profile.style.scss

fix: Responsivenes

---

backend/controllers/emailNotificationController.js
backend/routes/emailNotificationRouter.js

Reverts workshopapps/certificategenerator.web#574

Revert "fix: resolve error in send certificates"

---

frontend/src/Component/Footer/index.jsx
frontend/src/Component/Navbar/Dropdown/index.jsx
frontend/src/Component/Signup-Login/api.js
frontend/src/Component/Signup-Login/assets/Login.jsx
frontend/src/Component/Signup-Login/assets/Signup.jsx
frontend/src/Data/TermsOfService.js
frontend/src/api/axios.js
frontend/src/pages/BulkPreview/index.jsx
frontend/src/pages/Checkout/components/CheckoutMainLeft.jsx
frontend/src/pages/ComingSoon/index.jsx
frontend/src/pages/Dashboard/Generate/index.jsx
frontend/src/pages/Dashboard/Modal/EditModal/index.jsx
frontend/src/pages/Dashboard/Modal/ViewModal/index.jsx
frontend/src/pages/Dashboard/TableRow.jsx
frontend/src/pages/Dashboard/UploadCsv/index.jsx
frontend/src/pages/Dashboard/index.jsx
frontend/src/pages/Dashboard/utils/index.js
frontend/src/pages/ProfilePage/EditModal/index.jsx
frontend/src/pages/ProfilePage/index.jsx
frontend/src/pages/UploadCSV/index.jsx

chore: baseURL change

---

frontend/src/pages/BulkPreview/index.jsx
frontend/src/pages/Dashboard/Modal/ViewModal/index.jsx

The application can now send the certificates on the dashboard to each recipients' email address.

FRO-10: Send Certificate from dashboard, Consume the API to Send the Certificate

---

backend/controllers/userCertificateController.js

Added response and status code

	modified:   backend/controllers/userCertificateController.js

---

backend/controllers/authController.js
backend/controllers/userCertificateController.js
backend/models/certificateModel.js
backend/models/userModel.js
backend/routes/certificateRouter.js

Reverts workshopapps/certificategenerator.web#625

Revert "Certifcate model Upgrade and CRUD operations on certificate collections"
